table:
  name: grants
  schema: public
array_relationships:
  - name: users_grants
    using:
      foreign_key_constraint_on:
        column: grant_id
        table:
          name: users_grants
          schema: public
